feat: create service starknet-cashier + add starknet-testnet to docker-compose + improve CI (#74)
feat: add starknet-testnet to docker-compose
ci: improvements
refacto(node): split initialization code in multiple files

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -9,22 +9,41 @@ on:
 env:
   CARGO_TERM_COLOR: always
   ROOT_KEY: tprv8ZgxMBicQKsPeb6rodrmEXb1zRucvxYJgTKDhqQkZtbz8eY4Pf2EgbsT2swBXnnbDPQChQeFrFqHN72yFxzKfFAVsHdPeRWq2xqyUT2c4wH
-  SOCKET_PORT: 10001
-  GRPC_IP: "[::0]"
-  GRPC_PORT: 20001
-  SIGNER_URL: https://localhost:10001
+  SIGNER_GRPC_PORT: 10001
+  NODE_GRPC_PORT: 20001
+  # For node
   PG_URL: postgres://postgres:password@localhost:5432/node
+  SIGNER_URL: http://localhost:10001
 
 jobs:
-  build:
+  lint:
+    name: Lint
     runs-on: ubuntu-latest
-
+    steps:
+      - uses: actions/checkout@v4
+      - uses: dtolnay/rust-toolchain@1.85.0
+        with:
+          components: rustfmt, clippy
+      - uses: arduino/setup-protoc@v3
+        with:
+          version: "28.x"
+      - uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: "rust-cache-${{ hashFiles('**/Cargo.lock') }}"
+          cache-on-failure: true
+      - name: Check formatting
+        run: cargo fmt --all -- --check
+      - name: Run clippy
+        run: cargo clippy -- -D warnings
+  test:
+    name: Test
+    runs-on: ubuntu-latest
     services:
       db:
         image: postgres:15
         env:
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: password
+          POSTGRES_PASSWORD: 'password'
           POSTGRES_DB: node
         ports:
           - 5432:5432
@@ -33,60 +52,37 @@ jobs:
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
-
     steps:
       - uses: actions/checkout@v4
-
-      - name: Install Protoc
-        uses: arduino/setup-protoc@v3
+      - uses: dtolnay/rust-toolchain@1.85.0
+        with:
+          components: ""
+      - uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: "rust-cache-${{ hashFiles('**/Cargo.lock') }}"
+          cache-on-failure: true
+      - uses: arduino/setup-protoc@v3
         with:
           version: "28.x"
-
-      - name: Set up Rust cache
-        uses: Swatinem/rust-cache@v2
-
-      - name: Build
-        run: |
-          cargo build -p starknet-payment-indexer --all-targets --all-features
-          cargo build -p db-node --all-targets --all-features
-          cargo build -p nuts --all-targets --all-features
-          cargo build -p starknet-types --all-targets --all-features
-          cargo build -p node --all-targets --all-features
-          cargo build -p starknet-payment-indexer-bin --all-targets --all-features
-          cargo build -p signer --all-targets --all-features
-          cargo build -p cli-wallet --all-targets --all-features
-          cargo build -p wallet --all-targets --all-features
-
       - name: Run unit tests
+        run: cargo test --workspace --lib --bins
+      - name: Build services for integration tests
         run: |
-          cargo test -p starknet-payment-indexer --all-targets --all-features
-          cargo test -p db-node --all-targets --all-features
-          cargo test -p nuts --all-targets --all-features
-          cargo test -p starknet-types --all-targets --all-features
-          cargo test -p node --all-targets --all-features
-          cargo test -p starknet-payment-indexer-bin --all-targets --all-features
-          cargo test -p signer --all-targets --all-features
-          cargo test -p cli-wallet --all-targets --all-features
-          cargo test -p wallet --all-targets --all-features
-
-      - name: Run signer integration tests
+          cargo build -p signer --bin signer
+          cargo build -p node --no-default-features --bin node
+      - name: Run integration tests
+        timeout-minutes: 1
         run: |
-          cargo run --release --bin signer &
+          # Signer
+          GRPC_PORT=$SIGNER_GRPC_PORT cargo run -p signer --bin signer &
           SIGNER_RUN_PID=$!
-          while ! echo exit | nc localhost $SOCKET_PORT; do sleep 1; done
-          cargo test -p signer-tests
-          kill $SIGNER_RUN_PID
-
-      - name: Run node integration tests (with signer)
-        run: |
-          cargo run --release --bin signer &
-          SIGNER_RUN_PID=$!
-          while ! echo exit | nc localhost $SOCKET_PORT; do sleep 1; done
-          cargo run -p node --no-default-features --release --bin node -- --config ./crates/bin/node/config/local.toml &
+          while ! echo exit | nc localhost $SIGNER_GRPC_PORT; do sleep 1; done
+          GRPC_PORT=$SIGNER_GRPC_PORT cargo test -p signer-tests
+          # Node
+          GRPC_PORT=$NODE_GRPC_PORT cargo run -p node --no-default-features --bin node -- --config ./crates/bin/node/config/local.toml &
           NODE_RUN_PID=$!
-          while ! echo exit | nc localhost $GRPC_PORT; do sleep 1; done
-          cargo test -p node-tests
+          while ! echo exit | nc localhost $NODE_GRPC_PORT; do sleep 1; done
+          GRPC_PORT=$NODE_GRPC_PORT cargo test -p node-tests
+          # Cleanup
           kill $SIGNER_RUN_PID
           kill $NODE_RUN_PID
-
- 
